import Head from "next/head";
import Image from "next/image";
import Layout from "../components/Layout";
import ProgressBar from "../components/ProgressBar";
import Proyectos from "../components/Proyectos";
import { skills, proyectos } from "../profile.js";
import Link from "next/dist/client/link";
import styles from "../styles/github.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        {/* Header Card */}
        <header className="row">
          <div className="col-md-12 mb-4">
            <div className={styles.container}>
              <div className="card card-body bg-secondary text-light">
                <div className="row">
                  <div className="col-md-4">
                    <Image
                      alt="yo"
                      src="/img/yo-remove.png"
                      width={300}
                      height={280}
                    ></Image>
                  </div>
                  <div className="col-md-8">
                    <h1><b>Johan Alberto León Serrano</b></h1>
                    <h3><b>Desarrollador Web</b></h3>
                    <p>
                      Soy un estudiante en los últimos semestres de la carrera de Ingeniería en Sistemas con experiencia en el desarrollo web Full Stack, centrándome especialmente en el Front-End.
                    </p>
                    <p>
                      Mi objetivo es llevar mi carrera profesional al siguiente nivel en el ámbito laboral. Siempre estoy en busca de nuevos desafíos y busco aprender de cada experiencia para seguir creciendo como profesional.
                    </p>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </header>

        {/* Segunda seccion */}
        <div className="row py-2">
          <div className="col-md-4">
            <div className="card bg-light">
              <div className="card-body">
                <h1 className="text-center">Habilidades</h1>
                <hr />
                {skills.map(({ id, skill, porcentaje }) => (
                  <ProgressBar key={id} skill={skill} porcentaje={porcentaje} />
                ))}
              </div>
            </div>
            <br />
            <div className="card bg-light">
              <div className="card-body py-2">
                <h1 className="text-center">Contacto</h1>
                <hr />
                <h4>
                  {" "}
                  <b>Telefono Celular:</b> <p>+57 3006101322</p>{" "}
                </h4>
                <h4>
                  {" "}
                  <b>Correo electronico:</b> <p>johanleon991@gmail.com</p>{" "}
                </h4>
                <h4>
                  {" "}
                  <b>Linkedin:</b>{" "}
                  <a
                    href="https://www.linkedin.com/in/johan-alberto-leon-18b688229/"
                    target="__blank"
                  >
                    linkedin.com/in/johan-alberto-leon-18b688229/{" "}
                  </a>{" "}
                </h4>
                <br />
              </div>
            </div>
          </div>
          <div className="col-md-8">
            <div className="card bg-light">
              <div className="card-body">
                <h1 className="text-center">Experiencia</h1>
                <hr />
                <ul>
                  <li>
                    <h3>Desarrollador frontend Angular en Millenium group </h3>
                    <h4>Feb/2023-Abr/2023</h4>
                    <p>
                      Encargado de desarrollar vistas en Angular a partir de
                      consumir datos de Apis, principalmente orientado a la
                      creación de aplicaciones web mediante el framework de
                      Angular, solución de problemas de código y construcción de
                      vistas para las aplicaciones web.
                    </p>
                  </li>
                  <li>
                    <h3>
                      Desarrollador frontend en semillero de investigación VIRAL{" "}
                    </h3>
                    <h4>2018-Actualidad</h4>
                    <p>
                      Me encargue de desarrollar componentes frontend para la
                      página web del semillero de investigación de mi
                      universidad, manejaba tanto la parte de Backend con
                      NodeJS, también realizaba el enmaquetado básico con
                      Reactjs y Angular. <br />
                      Me encargaba del manejo de la base de datos la cual estaba
                      implementada en MySQL.
                    </p>
                  </li>
                </ul>
              </div>
            </div>
            <br />
            <div className="card bg-light">
              <div className="card-body">
                <h1 className="text-center">Proyectos</h1>
                <hr />
                <ul>
                  <li>
                    <h2>Mis proyectos personales los puedes ver aquí: </h2>
                    <h4>
                      <b>
                        Github:{" "}
                      </b>
                      <a
                        href="https://github.com/JohanLeon0914"
                        target="__blank"
                      >
                        {" "}
                        github.com/JohanLeon0914
                      </a>
                    </h4>
                    <h4>
                      <b>
                        Portafolio personal:{" "}
                      </b>
                      <a
                        href="https://new-portfolio-silk.vercel.app"
                        target="__blank"
                      >
                        {" "}
                        https://new-portfolio-silk.vercel.app
                      </a>
                    </h4>
                  </li>
                </ul>
              </div>
            </div>
            <br />
            <div className="card bg-light">
              <div className="card-body text-center">
                <h1>Formación educativa</h1>
                <h2>Universitaria:</h2>
                <h4>Universidad Fransisco de Paula Santander</h4>
                <h4>Jun 2018 - Actualidad</h4>
                <div className="col-auto p-5 text-center">
                  <Image
                    src="/img/UFPS_Logo.png"
                    alt="ufps-logo"
                    width={180}
                    height={248.5}
                  ></Image>
                  <h4>Ingeniería en sistemas</h4>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* portafolio */}
        <div className="row">
          <div className="col-md-12 p-4">
            <div className={styles.container}>
              <div className="card card-body bg-dark">
                <div className="row">
                  <div className="col-md-12">
                    <h1 className="text-center text-light">Portafolio</h1>
                  </div>
                  {proyectos.map(({ title, description, image, url }, i) => (
                    <Proyectos
                      key={i}
                      title={title}
                      descripcion={description}
                      image={image}
                      url={url}
                    />
                  ))}
                </div>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}
